name: Check

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  install_deps:
    name: Install dependencies
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

  check:
    name: Check code
    runs-on: ubuntu-latest

    needs: install_deps

    steps:
      - name: Prettier check
        run: npx prettier --check "src/**/*.{ts,tsx}"

      - name: Linter check
        run: npx eslint "src/**/*.{ts,tsx}"
