name: Deploy

on:
  push:
    branches:
      - main

jobs:
  install_deps:
    name: Install dependencies
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

  check:
    name: Check code
    runs-on: ubuntu-latest

    needs: install_deps

    steps:
      - name: Prettier check
        run: npx prettier --check "src/**/*.{ts,tsx}"

      - name: Linter check
        run: npx eslint "src/**/*.{ts,tsx}"

  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    needs: [install_deps, check]

    steps:
      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
